// ---------------------------------------------------------------------------
// 6-letter word list for submit-button validation (valid wrong guesses).
// Puzzle answers and final words are auto-accepted by the game engine
// regardless of whether they appear here, so you do not need to add every
// puzzle answer manually.  Add words here only if you want additional
// non-answer guesses to be accepted.
// All entries must be lowercase, exactly 6 characters.
// ---------------------------------------------------------------------------

const WORD_LIST = new Set([
  // ── Puzzle words (always include every answer and finalWord) ──────────────
  "closet","fridge","carpet","pantry","shower","garden",
  "flower","throne","prance",

  // ── Household / home ─────────────────────────────────────────────────────
  "alcove","boiler","bureau","candle","cellar","closet","corset",
  "drafty","drapes","faucet","gravel","hamper","hearth","kettle",
  "linen","locker","mantel","mantle","marble","mirror","mortar",
  "parlor","pastry","pillow","plinth","settee","siding","soften",
  "sunlit","tiling","towels","veneer","wicker","wicket","window",

  // ── Common English words ─────────────────────────────────────────────────
  "absent","accept","access","action","active","actual","afford",
  "afraid","agency","agenda","almost","always","amount","animal",
  "answer","anyone","anyway","appear","around","artist","asking",
  "aspect","assume","august","author","avenue",
  "backed","battle","beauty","before","begins","behind","belong",
  "better","beyond","bitter","blight","bought","bridge","bright",
  "broken","bronze","burden","buying",
  "called","cancel","cannot","castle","casual","cattle","caught",
  "center","change","charge","charts","choose","circle","cities",
  "client","closed","coffee","coming","common","corner","couple",
  "custom",
  "damage","danger","deadly","decide","demand","desire","detail",
  "device","direct","divide","dollar","double","during",
  "editor","effect","emerge","empire","ending","energy","enough",
  "entire","escape","except","expand","expect","export","extend",
  "fabric","factor","failed","fairly","family","famous","figure",
  "filled","finger","flight","follow","forest","formal","fought",
  "frozen","future",
  "gained","giving","global","golden","govern","ground",
  "happen","health","helped","hidden","higher",
  "impact","income","indeed","inside","island",
  "joined","junior",
  "killed",
  "latest","launch","leader","length","lights","likely","listen",
  "little","losing",
  "mainly","manage","manner","market","matter","member","mobile",
  "moment","months","mostly","murder","mutual",
  "narrow","nation","nature","nearly","needed","normal","notice",
  "object","office","online","opened","option","others",
  "parent","passed","people","period","phrase","places","planet",
  "played","player","points","policy","posted","prefer","pretty",
  "profit","proper","public","pushed",
  "raised","random","rather","really","reason","record","reduce",
  "reform","relief","remain","remove","report","return","review",
  "rocket","rubber","ruling",
  "sector","should","simply","single","smooth","social","sought",
  "spirit","strong","struck","system",
  "talent","theory","though","taking","trying","turned",
  "unable","update","useful",
  "varied","voting",
  "waited","wanted","within","wonder","worked",
  "yellow",

  // ── More common words ────────────────────────────────────────────────────
  "across","affect","bright","chairs","chairs","chairs",
  "choice","chosen","church","caught","clever","closet","column",
  "covers","credit","crisis","custom","cycles",
  "danger","dating","design","dollar","donate","driver","during",
  "eating","editor","either","ending","engage","entire","equals",
  "errors","estate","events","evenly","except","expect","expire",
  "failed","famine","finger","finish","fiscal","flying","format",
  "formed","frozen","future",
  "gender","giving","global","gloves","grades","grants","grapes",
  "growth","guards","guests","guided","guides","guilty",
  "harder","hardly","harmed","hearts","heroes","heroin","hiding",
  "hiring","hosted","hotels","houses","hunger","hunter","hybrid",
  "ignore","impact","impose","inform","inputs","inside","intake",
  "intent","invest","issues",
  "joined","joined","judges","junior","justice",
  "kindly","knight","knives","launch",
  "layers","leader","league","learns","leaves","levels","limits",
  "listen","losing","losers","lovers","loving","lowest","lyrics",
  "makers","making","margin","master","maximal","medium","mental",
  "method","mighty","missed","mixing","mostly","motion","moving",
  "myself",
  "naming","nearby","nicely","nights","noting","novels",
  "obtain","occurs","offers","opened","orders","origin","output",
  "owners",
  "packed","paging","papers","paying","paints","panels","passes",
  "paying","permit","photos","picked","pieces","played","plenty",
  "plugin","police","pooled","postal","powers","prince","prison",
  "proven","purely","pursue",
  "queens","quoted","quotes",
  "racial","ranked","rarely","rating","reach","reading","really",
  "recent","refers","regime","reject","rental","rental","repair",
  "repeat","rescue","resist","return","rights","rising","rivers",
  "robust","rocket","rolled","rounds","rulers","rushed",
  "safety","sample","saving","saying","search","seeing","select",
  "seller","senior","series","serves","shared","shares","sheets",
  "shifts","ships","should","signal","simple","skills","slaves",
  "slides","slight","slowly","slight","spoken","sports","spread",
  "starts","stated","states","steady","stones","stored","stores",
  "strife","struck","styles","submit","surely","surplus","switch",
  "tables","tackle","taking","taught","target","tested","thinks",
  "thirds","thrown","tigers","timing","tipped","titled","token",
  "topics","toward","travel","tricks","tried","troops","trying",
  "tunnel","typing",
  "unless","unlike","update","useful","users",
  "valued","values","vendor","verbal","vested","viable","videos",
  "viewed","virtue","vision","visits","visual","voting",
  "walked","warmth","wealth","weight","wholly","widely","writer",
  "writes","yields",
]);
